// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: query.proto

#include "query.pb.h"
#include "query.grpc.pb.h"

#include <functional>
#include <grpcpp/impl/codegen/async_stream.h>
#include <grpcpp/impl/codegen/async_unary_call.h>
#include <grpcpp/impl/codegen/channel_interface.h>
#include <grpcpp/impl/codegen/client_unary_call.h>
#include <grpcpp/impl/codegen/client_callback.h>
#include <grpcpp/impl/codegen/message_allocator.h>
#include <grpcpp/impl/codegen/method_handler.h>
#include <grpcpp/impl/codegen/rpc_service_method.h>
#include <grpcpp/impl/codegen/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/impl/codegen/server_context.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/sync_stream.h>
namespace dbquery {

static const char* Query_method_names[] = {
  "/dbquery.Query/SendDCFInit",
  "/dbquery.Query/SendDPFInit",
  "/dbquery.Query/SendATInit",
  "/dbquery.Query/SendListInit",
  "/dbquery.Query/SendDCFUpdate",
  "/dbquery.Query/SendDCFBatchedUpdate",
  "/dbquery.Query/SendDPFUpdate",
  "/dbquery.Query/SendDPFBatchedUpdate",
  "/dbquery.Query/SendListUpdate",
  "/dbquery.Query/SendListBatchedUpdate",
  "/dbquery.Query/SendATAppend1",
  "/dbquery.Query/SendATAppend2",
  "/dbquery.Query/SendDCFQuery",
  "/dbquery.Query/SendATQuery",
  "/dbquery.Query/SendAggQuery",
  "/dbquery.Query/SendVBAggQuery",
  "/dbquery.Query/SendOneHotTableUpdate",
  "/dbquery.Query/SendOneHotTableBatchUpdate",
  "/dbquery.Query/SendOneHotTableInit",
  "/dbquery.Query/SendBOTableInit",
  "/dbquery.Query/SendBOTableUpdate",
  "/dbquery.Query/SendBOTableBatchUpdate",
  "/dbquery.Query/SendBOAggQuery",
  "/dbquery.Query/SendVBFSSAggQuery",
  "/dbquery.Query/SendBOFSSAggQuery",
};

std::unique_ptr< Query::Stub> Query::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< Query::Stub> stub(new Query::Stub(channel, options));
  return stub;
}

Query::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options)
  : channel_(channel), rpcmethod_SendDCFInit_(Query_method_names[0], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_SendDPFInit_(Query_method_names[1], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_SendATInit_(Query_method_names[2], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_SendListInit_(Query_method_names[3], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_SendDCFUpdate_(Query_method_names[4], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_SendDCFBatchedUpdate_(Query_method_names[5], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_SendDPFUpdate_(Query_method_names[6], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_SendDPFBatchedUpdate_(Query_method_names[7], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_SendListUpdate_(Query_method_names[8], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_SendListBatchedUpdate_(Query_method_names[9], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_SendATAppend1_(Query_method_names[10], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_SendATAppend2_(Query_method_names[11], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_SendDCFQuery_(Query_method_names[12], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_SendATQuery_(Query_method_names[13], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_SendAggQuery_(Query_method_names[14], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_SendVBAggQuery_(Query_method_names[15], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_SendOneHotTableUpdate_(Query_method_names[16], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_SendOneHotTableBatchUpdate_(Query_method_names[17], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_SendOneHotTableInit_(Query_method_names[18], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_SendBOTableInit_(Query_method_names[19], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_SendBOTableUpdate_(Query_method_names[20], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_SendBOTableBatchUpdate_(Query_method_names[21], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_SendBOAggQuery_(Query_method_names[22], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_SendVBFSSAggQuery_(Query_method_names[23], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_SendBOFSSAggQuery_(Query_method_names[24], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status Query::Stub::SendDCFInit(::grpc::ClientContext* context, const ::dbquery::InitDCFRequest& request, ::dbquery::InitDCFResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::dbquery::InitDCFRequest, ::dbquery::InitDCFResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_SendDCFInit_, context, request, response);
}

void Query::Stub::async::SendDCFInit(::grpc::ClientContext* context, const ::dbquery::InitDCFRequest* request, ::dbquery::InitDCFResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::dbquery::InitDCFRequest, ::dbquery::InitDCFResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_SendDCFInit_, context, request, response, std::move(f));
}

void Query::Stub::async::SendDCFInit(::grpc::ClientContext* context, const ::dbquery::InitDCFRequest* request, ::dbquery::InitDCFResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_SendDCFInit_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::dbquery::InitDCFResponse>* Query::Stub::PrepareAsyncSendDCFInitRaw(::grpc::ClientContext* context, const ::dbquery::InitDCFRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::dbquery::InitDCFResponse, ::dbquery::InitDCFRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_SendDCFInit_, context, request);
}

::grpc::ClientAsyncResponseReader< ::dbquery::InitDCFResponse>* Query::Stub::AsyncSendDCFInitRaw(::grpc::ClientContext* context, const ::dbquery::InitDCFRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncSendDCFInitRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status Query::Stub::SendDPFInit(::grpc::ClientContext* context, const ::dbquery::InitDPFRequest& request, ::dbquery::InitDPFResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::dbquery::InitDPFRequest, ::dbquery::InitDPFResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_SendDPFInit_, context, request, response);
}

void Query::Stub::async::SendDPFInit(::grpc::ClientContext* context, const ::dbquery::InitDPFRequest* request, ::dbquery::InitDPFResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::dbquery::InitDPFRequest, ::dbquery::InitDPFResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_SendDPFInit_, context, request, response, std::move(f));
}

void Query::Stub::async::SendDPFInit(::grpc::ClientContext* context, const ::dbquery::InitDPFRequest* request, ::dbquery::InitDPFResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_SendDPFInit_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::dbquery::InitDPFResponse>* Query::Stub::PrepareAsyncSendDPFInitRaw(::grpc::ClientContext* context, const ::dbquery::InitDPFRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::dbquery::InitDPFResponse, ::dbquery::InitDPFRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_SendDPFInit_, context, request);
}

::grpc::ClientAsyncResponseReader< ::dbquery::InitDPFResponse>* Query::Stub::AsyncSendDPFInitRaw(::grpc::ClientContext* context, const ::dbquery::InitDPFRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncSendDPFInitRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status Query::Stub::SendATInit(::grpc::ClientContext* context, const ::dbquery::InitATRequest& request, ::dbquery::InitATResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::dbquery::InitATRequest, ::dbquery::InitATResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_SendATInit_, context, request, response);
}

void Query::Stub::async::SendATInit(::grpc::ClientContext* context, const ::dbquery::InitATRequest* request, ::dbquery::InitATResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::dbquery::InitATRequest, ::dbquery::InitATResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_SendATInit_, context, request, response, std::move(f));
}

void Query::Stub::async::SendATInit(::grpc::ClientContext* context, const ::dbquery::InitATRequest* request, ::dbquery::InitATResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_SendATInit_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::dbquery::InitATResponse>* Query::Stub::PrepareAsyncSendATInitRaw(::grpc::ClientContext* context, const ::dbquery::InitATRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::dbquery::InitATResponse, ::dbquery::InitATRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_SendATInit_, context, request);
}

::grpc::ClientAsyncResponseReader< ::dbquery::InitATResponse>* Query::Stub::AsyncSendATInitRaw(::grpc::ClientContext* context, const ::dbquery::InitATRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncSendATInitRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status Query::Stub::SendListInit(::grpc::ClientContext* context, const ::dbquery::InitListRequest& request, ::dbquery::InitListResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::dbquery::InitListRequest, ::dbquery::InitListResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_SendListInit_, context, request, response);
}

void Query::Stub::async::SendListInit(::grpc::ClientContext* context, const ::dbquery::InitListRequest* request, ::dbquery::InitListResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::dbquery::InitListRequest, ::dbquery::InitListResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_SendListInit_, context, request, response, std::move(f));
}

void Query::Stub::async::SendListInit(::grpc::ClientContext* context, const ::dbquery::InitListRequest* request, ::dbquery::InitListResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_SendListInit_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::dbquery::InitListResponse>* Query::Stub::PrepareAsyncSendListInitRaw(::grpc::ClientContext* context, const ::dbquery::InitListRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::dbquery::InitListResponse, ::dbquery::InitListRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_SendListInit_, context, request);
}

::grpc::ClientAsyncResponseReader< ::dbquery::InitListResponse>* Query::Stub::AsyncSendListInitRaw(::grpc::ClientContext* context, const ::dbquery::InitListRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncSendListInitRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status Query::Stub::SendDCFUpdate(::grpc::ClientContext* context, const ::dbquery::UpdateDCFRequest& request, ::dbquery::UpdateDCFResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::dbquery::UpdateDCFRequest, ::dbquery::UpdateDCFResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_SendDCFUpdate_, context, request, response);
}

void Query::Stub::async::SendDCFUpdate(::grpc::ClientContext* context, const ::dbquery::UpdateDCFRequest* request, ::dbquery::UpdateDCFResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::dbquery::UpdateDCFRequest, ::dbquery::UpdateDCFResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_SendDCFUpdate_, context, request, response, std::move(f));
}

void Query::Stub::async::SendDCFUpdate(::grpc::ClientContext* context, const ::dbquery::UpdateDCFRequest* request, ::dbquery::UpdateDCFResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_SendDCFUpdate_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::dbquery::UpdateDCFResponse>* Query::Stub::PrepareAsyncSendDCFUpdateRaw(::grpc::ClientContext* context, const ::dbquery::UpdateDCFRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::dbquery::UpdateDCFResponse, ::dbquery::UpdateDCFRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_SendDCFUpdate_, context, request);
}

::grpc::ClientAsyncResponseReader< ::dbquery::UpdateDCFResponse>* Query::Stub::AsyncSendDCFUpdateRaw(::grpc::ClientContext* context, const ::dbquery::UpdateDCFRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncSendDCFUpdateRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status Query::Stub::SendDCFBatchedUpdate(::grpc::ClientContext* context, const ::dbquery::BatchedUpdateDCFRequest& request, ::dbquery::BatchedUpdateDCFResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::dbquery::BatchedUpdateDCFRequest, ::dbquery::BatchedUpdateDCFResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_SendDCFBatchedUpdate_, context, request, response);
}

void Query::Stub::async::SendDCFBatchedUpdate(::grpc::ClientContext* context, const ::dbquery::BatchedUpdateDCFRequest* request, ::dbquery::BatchedUpdateDCFResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::dbquery::BatchedUpdateDCFRequest, ::dbquery::BatchedUpdateDCFResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_SendDCFBatchedUpdate_, context, request, response, std::move(f));
}

void Query::Stub::async::SendDCFBatchedUpdate(::grpc::ClientContext* context, const ::dbquery::BatchedUpdateDCFRequest* request, ::dbquery::BatchedUpdateDCFResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_SendDCFBatchedUpdate_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::dbquery::BatchedUpdateDCFResponse>* Query::Stub::PrepareAsyncSendDCFBatchedUpdateRaw(::grpc::ClientContext* context, const ::dbquery::BatchedUpdateDCFRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::dbquery::BatchedUpdateDCFResponse, ::dbquery::BatchedUpdateDCFRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_SendDCFBatchedUpdate_, context, request);
}

::grpc::ClientAsyncResponseReader< ::dbquery::BatchedUpdateDCFResponse>* Query::Stub::AsyncSendDCFBatchedUpdateRaw(::grpc::ClientContext* context, const ::dbquery::BatchedUpdateDCFRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncSendDCFBatchedUpdateRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status Query::Stub::SendDPFUpdate(::grpc::ClientContext* context, const ::dbquery::UpdateDPFRequest& request, ::dbquery::UpdateDPFResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::dbquery::UpdateDPFRequest, ::dbquery::UpdateDPFResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_SendDPFUpdate_, context, request, response);
}

void Query::Stub::async::SendDPFUpdate(::grpc::ClientContext* context, const ::dbquery::UpdateDPFRequest* request, ::dbquery::UpdateDPFResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::dbquery::UpdateDPFRequest, ::dbquery::UpdateDPFResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_SendDPFUpdate_, context, request, response, std::move(f));
}

void Query::Stub::async::SendDPFUpdate(::grpc::ClientContext* context, const ::dbquery::UpdateDPFRequest* request, ::dbquery::UpdateDPFResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_SendDPFUpdate_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::dbquery::UpdateDPFResponse>* Query::Stub::PrepareAsyncSendDPFUpdateRaw(::grpc::ClientContext* context, const ::dbquery::UpdateDPFRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::dbquery::UpdateDPFResponse, ::dbquery::UpdateDPFRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_SendDPFUpdate_, context, request);
}

::grpc::ClientAsyncResponseReader< ::dbquery::UpdateDPFResponse>* Query::Stub::AsyncSendDPFUpdateRaw(::grpc::ClientContext* context, const ::dbquery::UpdateDPFRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncSendDPFUpdateRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status Query::Stub::SendDPFBatchedUpdate(::grpc::ClientContext* context, const ::dbquery::BatchedUpdateDPFRequest& request, ::dbquery::BatchedUpdateDPFResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::dbquery::BatchedUpdateDPFRequest, ::dbquery::BatchedUpdateDPFResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_SendDPFBatchedUpdate_, context, request, response);
}

void Query::Stub::async::SendDPFBatchedUpdate(::grpc::ClientContext* context, const ::dbquery::BatchedUpdateDPFRequest* request, ::dbquery::BatchedUpdateDPFResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::dbquery::BatchedUpdateDPFRequest, ::dbquery::BatchedUpdateDPFResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_SendDPFBatchedUpdate_, context, request, response, std::move(f));
}

void Query::Stub::async::SendDPFBatchedUpdate(::grpc::ClientContext* context, const ::dbquery::BatchedUpdateDPFRequest* request, ::dbquery::BatchedUpdateDPFResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_SendDPFBatchedUpdate_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::dbquery::BatchedUpdateDPFResponse>* Query::Stub::PrepareAsyncSendDPFBatchedUpdateRaw(::grpc::ClientContext* context, const ::dbquery::BatchedUpdateDPFRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::dbquery::BatchedUpdateDPFResponse, ::dbquery::BatchedUpdateDPFRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_SendDPFBatchedUpdate_, context, request);
}

::grpc::ClientAsyncResponseReader< ::dbquery::BatchedUpdateDPFResponse>* Query::Stub::AsyncSendDPFBatchedUpdateRaw(::grpc::ClientContext* context, const ::dbquery::BatchedUpdateDPFRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncSendDPFBatchedUpdateRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status Query::Stub::SendListUpdate(::grpc::ClientContext* context, const ::dbquery::UpdateListRequest& request, ::dbquery::UpdateListResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::dbquery::UpdateListRequest, ::dbquery::UpdateListResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_SendListUpdate_, context, request, response);
}

void Query::Stub::async::SendListUpdate(::grpc::ClientContext* context, const ::dbquery::UpdateListRequest* request, ::dbquery::UpdateListResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::dbquery::UpdateListRequest, ::dbquery::UpdateListResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_SendListUpdate_, context, request, response, std::move(f));
}

void Query::Stub::async::SendListUpdate(::grpc::ClientContext* context, const ::dbquery::UpdateListRequest* request, ::dbquery::UpdateListResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_SendListUpdate_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::dbquery::UpdateListResponse>* Query::Stub::PrepareAsyncSendListUpdateRaw(::grpc::ClientContext* context, const ::dbquery::UpdateListRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::dbquery::UpdateListResponse, ::dbquery::UpdateListRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_SendListUpdate_, context, request);
}

::grpc::ClientAsyncResponseReader< ::dbquery::UpdateListResponse>* Query::Stub::AsyncSendListUpdateRaw(::grpc::ClientContext* context, const ::dbquery::UpdateListRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncSendListUpdateRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status Query::Stub::SendListBatchedUpdate(::grpc::ClientContext* context, const ::dbquery::BatchedUpdateListRequest& request, ::dbquery::BatchedUpdateListResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::dbquery::BatchedUpdateListRequest, ::dbquery::BatchedUpdateListResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_SendListBatchedUpdate_, context, request, response);
}

void Query::Stub::async::SendListBatchedUpdate(::grpc::ClientContext* context, const ::dbquery::BatchedUpdateListRequest* request, ::dbquery::BatchedUpdateListResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::dbquery::BatchedUpdateListRequest, ::dbquery::BatchedUpdateListResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_SendListBatchedUpdate_, context, request, response, std::move(f));
}

void Query::Stub::async::SendListBatchedUpdate(::grpc::ClientContext* context, const ::dbquery::BatchedUpdateListRequest* request, ::dbquery::BatchedUpdateListResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_SendListBatchedUpdate_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::dbquery::BatchedUpdateListResponse>* Query::Stub::PrepareAsyncSendListBatchedUpdateRaw(::grpc::ClientContext* context, const ::dbquery::BatchedUpdateListRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::dbquery::BatchedUpdateListResponse, ::dbquery::BatchedUpdateListRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_SendListBatchedUpdate_, context, request);
}

::grpc::ClientAsyncResponseReader< ::dbquery::BatchedUpdateListResponse>* Query::Stub::AsyncSendListBatchedUpdateRaw(::grpc::ClientContext* context, const ::dbquery::BatchedUpdateListRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncSendListBatchedUpdateRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status Query::Stub::SendATAppend1(::grpc::ClientContext* context, const ::dbquery::AppendAT1Request& request, ::dbquery::AppendAT1Response* response) {
  return ::grpc::internal::BlockingUnaryCall< ::dbquery::AppendAT1Request, ::dbquery::AppendAT1Response, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_SendATAppend1_, context, request, response);
}

void Query::Stub::async::SendATAppend1(::grpc::ClientContext* context, const ::dbquery::AppendAT1Request* request, ::dbquery::AppendAT1Response* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::dbquery::AppendAT1Request, ::dbquery::AppendAT1Response, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_SendATAppend1_, context, request, response, std::move(f));
}

void Query::Stub::async::SendATAppend1(::grpc::ClientContext* context, const ::dbquery::AppendAT1Request* request, ::dbquery::AppendAT1Response* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_SendATAppend1_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::dbquery::AppendAT1Response>* Query::Stub::PrepareAsyncSendATAppend1Raw(::grpc::ClientContext* context, const ::dbquery::AppendAT1Request& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::dbquery::AppendAT1Response, ::dbquery::AppendAT1Request, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_SendATAppend1_, context, request);
}

::grpc::ClientAsyncResponseReader< ::dbquery::AppendAT1Response>* Query::Stub::AsyncSendATAppend1Raw(::grpc::ClientContext* context, const ::dbquery::AppendAT1Request& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncSendATAppend1Raw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status Query::Stub::SendATAppend2(::grpc::ClientContext* context, const ::dbquery::AppendAT2Request& request, ::dbquery::AppendAT2Response* response) {
  return ::grpc::internal::BlockingUnaryCall< ::dbquery::AppendAT2Request, ::dbquery::AppendAT2Response, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_SendATAppend2_, context, request, response);
}

void Query::Stub::async::SendATAppend2(::grpc::ClientContext* context, const ::dbquery::AppendAT2Request* request, ::dbquery::AppendAT2Response* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::dbquery::AppendAT2Request, ::dbquery::AppendAT2Response, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_SendATAppend2_, context, request, response, std::move(f));
}

void Query::Stub::async::SendATAppend2(::grpc::ClientContext* context, const ::dbquery::AppendAT2Request* request, ::dbquery::AppendAT2Response* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_SendATAppend2_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::dbquery::AppendAT2Response>* Query::Stub::PrepareAsyncSendATAppend2Raw(::grpc::ClientContext* context, const ::dbquery::AppendAT2Request& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::dbquery::AppendAT2Response, ::dbquery::AppendAT2Request, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_SendATAppend2_, context, request);
}

::grpc::ClientAsyncResponseReader< ::dbquery::AppendAT2Response>* Query::Stub::AsyncSendATAppend2Raw(::grpc::ClientContext* context, const ::dbquery::AppendAT2Request& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncSendATAppend2Raw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status Query::Stub::SendDCFQuery(::grpc::ClientContext* context, const ::dbquery::QueryDCFRequest& request, ::dbquery::QueryDCFResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::dbquery::QueryDCFRequest, ::dbquery::QueryDCFResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_SendDCFQuery_, context, request, response);
}

void Query::Stub::async::SendDCFQuery(::grpc::ClientContext* context, const ::dbquery::QueryDCFRequest* request, ::dbquery::QueryDCFResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::dbquery::QueryDCFRequest, ::dbquery::QueryDCFResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_SendDCFQuery_, context, request, response, std::move(f));
}

void Query::Stub::async::SendDCFQuery(::grpc::ClientContext* context, const ::dbquery::QueryDCFRequest* request, ::dbquery::QueryDCFResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_SendDCFQuery_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::dbquery::QueryDCFResponse>* Query::Stub::PrepareAsyncSendDCFQueryRaw(::grpc::ClientContext* context, const ::dbquery::QueryDCFRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::dbquery::QueryDCFResponse, ::dbquery::QueryDCFRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_SendDCFQuery_, context, request);
}

::grpc::ClientAsyncResponseReader< ::dbquery::QueryDCFResponse>* Query::Stub::AsyncSendDCFQueryRaw(::grpc::ClientContext* context, const ::dbquery::QueryDCFRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncSendDCFQueryRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status Query::Stub::SendATQuery(::grpc::ClientContext* context, const ::dbquery::QueryATRequest& request, ::dbquery::QueryATResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::dbquery::QueryATRequest, ::dbquery::QueryATResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_SendATQuery_, context, request, response);
}

void Query::Stub::async::SendATQuery(::grpc::ClientContext* context, const ::dbquery::QueryATRequest* request, ::dbquery::QueryATResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::dbquery::QueryATRequest, ::dbquery::QueryATResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_SendATQuery_, context, request, response, std::move(f));
}

void Query::Stub::async::SendATQuery(::grpc::ClientContext* context, const ::dbquery::QueryATRequest* request, ::dbquery::QueryATResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_SendATQuery_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::dbquery::QueryATResponse>* Query::Stub::PrepareAsyncSendATQueryRaw(::grpc::ClientContext* context, const ::dbquery::QueryATRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::dbquery::QueryATResponse, ::dbquery::QueryATRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_SendATQuery_, context, request);
}

::grpc::ClientAsyncResponseReader< ::dbquery::QueryATResponse>* Query::Stub::AsyncSendATQueryRaw(::grpc::ClientContext* context, const ::dbquery::QueryATRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncSendATQueryRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status Query::Stub::SendAggQuery(::grpc::ClientContext* context, const ::dbquery::QueryAggRequest& request, ::dbquery::QueryAggResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::dbquery::QueryAggRequest, ::dbquery::QueryAggResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_SendAggQuery_, context, request, response);
}

void Query::Stub::async::SendAggQuery(::grpc::ClientContext* context, const ::dbquery::QueryAggRequest* request, ::dbquery::QueryAggResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::dbquery::QueryAggRequest, ::dbquery::QueryAggResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_SendAggQuery_, context, request, response, std::move(f));
}

void Query::Stub::async::SendAggQuery(::grpc::ClientContext* context, const ::dbquery::QueryAggRequest* request, ::dbquery::QueryAggResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_SendAggQuery_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::dbquery::QueryAggResponse>* Query::Stub::PrepareAsyncSendAggQueryRaw(::grpc::ClientContext* context, const ::dbquery::QueryAggRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::dbquery::QueryAggResponse, ::dbquery::QueryAggRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_SendAggQuery_, context, request);
}

::grpc::ClientAsyncResponseReader< ::dbquery::QueryAggResponse>* Query::Stub::AsyncSendAggQueryRaw(::grpc::ClientContext* context, const ::dbquery::QueryAggRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncSendAggQueryRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status Query::Stub::SendVBAggQuery(::grpc::ClientContext* context, const ::dbquery::QueryVBAggRequest& request, ::dbquery::QueryVBAggResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::dbquery::QueryVBAggRequest, ::dbquery::QueryVBAggResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_SendVBAggQuery_, context, request, response);
}

void Query::Stub::async::SendVBAggQuery(::grpc::ClientContext* context, const ::dbquery::QueryVBAggRequest* request, ::dbquery::QueryVBAggResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::dbquery::QueryVBAggRequest, ::dbquery::QueryVBAggResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_SendVBAggQuery_, context, request, response, std::move(f));
}

void Query::Stub::async::SendVBAggQuery(::grpc::ClientContext* context, const ::dbquery::QueryVBAggRequest* request, ::dbquery::QueryVBAggResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_SendVBAggQuery_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::dbquery::QueryVBAggResponse>* Query::Stub::PrepareAsyncSendVBAggQueryRaw(::grpc::ClientContext* context, const ::dbquery::QueryVBAggRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::dbquery::QueryVBAggResponse, ::dbquery::QueryVBAggRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_SendVBAggQuery_, context, request);
}

::grpc::ClientAsyncResponseReader< ::dbquery::QueryVBAggResponse>* Query::Stub::AsyncSendVBAggQueryRaw(::grpc::ClientContext* context, const ::dbquery::QueryVBAggRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncSendVBAggQueryRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status Query::Stub::SendOneHotTableUpdate(::grpc::ClientContext* context, const ::dbquery::UpdateOneHotTableRequest& request, ::dbquery::UpdateOneHotTableResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::dbquery::UpdateOneHotTableRequest, ::dbquery::UpdateOneHotTableResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_SendOneHotTableUpdate_, context, request, response);
}

void Query::Stub::async::SendOneHotTableUpdate(::grpc::ClientContext* context, const ::dbquery::UpdateOneHotTableRequest* request, ::dbquery::UpdateOneHotTableResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::dbquery::UpdateOneHotTableRequest, ::dbquery::UpdateOneHotTableResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_SendOneHotTableUpdate_, context, request, response, std::move(f));
}

void Query::Stub::async::SendOneHotTableUpdate(::grpc::ClientContext* context, const ::dbquery::UpdateOneHotTableRequest* request, ::dbquery::UpdateOneHotTableResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_SendOneHotTableUpdate_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::dbquery::UpdateOneHotTableResponse>* Query::Stub::PrepareAsyncSendOneHotTableUpdateRaw(::grpc::ClientContext* context, const ::dbquery::UpdateOneHotTableRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::dbquery::UpdateOneHotTableResponse, ::dbquery::UpdateOneHotTableRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_SendOneHotTableUpdate_, context, request);
}

::grpc::ClientAsyncResponseReader< ::dbquery::UpdateOneHotTableResponse>* Query::Stub::AsyncSendOneHotTableUpdateRaw(::grpc::ClientContext* context, const ::dbquery::UpdateOneHotTableRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncSendOneHotTableUpdateRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status Query::Stub::SendOneHotTableBatchUpdate(::grpc::ClientContext* context, const ::dbquery::UpdateOneHotTableBatchRequest& request, ::dbquery::UpdateOneHotTableBatchResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::dbquery::UpdateOneHotTableBatchRequest, ::dbquery::UpdateOneHotTableBatchResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_SendOneHotTableBatchUpdate_, context, request, response);
}

void Query::Stub::async::SendOneHotTableBatchUpdate(::grpc::ClientContext* context, const ::dbquery::UpdateOneHotTableBatchRequest* request, ::dbquery::UpdateOneHotTableBatchResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::dbquery::UpdateOneHotTableBatchRequest, ::dbquery::UpdateOneHotTableBatchResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_SendOneHotTableBatchUpdate_, context, request, response, std::move(f));
}

void Query::Stub::async::SendOneHotTableBatchUpdate(::grpc::ClientContext* context, const ::dbquery::UpdateOneHotTableBatchRequest* request, ::dbquery::UpdateOneHotTableBatchResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_SendOneHotTableBatchUpdate_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::dbquery::UpdateOneHotTableBatchResponse>* Query::Stub::PrepareAsyncSendOneHotTableBatchUpdateRaw(::grpc::ClientContext* context, const ::dbquery::UpdateOneHotTableBatchRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::dbquery::UpdateOneHotTableBatchResponse, ::dbquery::UpdateOneHotTableBatchRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_SendOneHotTableBatchUpdate_, context, request);
}

::grpc::ClientAsyncResponseReader< ::dbquery::UpdateOneHotTableBatchResponse>* Query::Stub::AsyncSendOneHotTableBatchUpdateRaw(::grpc::ClientContext* context, const ::dbquery::UpdateOneHotTableBatchRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncSendOneHotTableBatchUpdateRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status Query::Stub::SendOneHotTableInit(::grpc::ClientContext* context, const ::dbquery::InitOneHotTableRequest& request, ::dbquery::InitOneHotTableResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::dbquery::InitOneHotTableRequest, ::dbquery::InitOneHotTableResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_SendOneHotTableInit_, context, request, response);
}

void Query::Stub::async::SendOneHotTableInit(::grpc::ClientContext* context, const ::dbquery::InitOneHotTableRequest* request, ::dbquery::InitOneHotTableResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::dbquery::InitOneHotTableRequest, ::dbquery::InitOneHotTableResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_SendOneHotTableInit_, context, request, response, std::move(f));
}

void Query::Stub::async::SendOneHotTableInit(::grpc::ClientContext* context, const ::dbquery::InitOneHotTableRequest* request, ::dbquery::InitOneHotTableResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_SendOneHotTableInit_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::dbquery::InitOneHotTableResponse>* Query::Stub::PrepareAsyncSendOneHotTableInitRaw(::grpc::ClientContext* context, const ::dbquery::InitOneHotTableRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::dbquery::InitOneHotTableResponse, ::dbquery::InitOneHotTableRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_SendOneHotTableInit_, context, request);
}

::grpc::ClientAsyncResponseReader< ::dbquery::InitOneHotTableResponse>* Query::Stub::AsyncSendOneHotTableInitRaw(::grpc::ClientContext* context, const ::dbquery::InitOneHotTableRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncSendOneHotTableInitRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status Query::Stub::SendBOTableInit(::grpc::ClientContext* context, const ::dbquery::InitBOTableRequest& request, ::dbquery::InitBOTableResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::dbquery::InitBOTableRequest, ::dbquery::InitBOTableResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_SendBOTableInit_, context, request, response);
}

void Query::Stub::async::SendBOTableInit(::grpc::ClientContext* context, const ::dbquery::InitBOTableRequest* request, ::dbquery::InitBOTableResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::dbquery::InitBOTableRequest, ::dbquery::InitBOTableResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_SendBOTableInit_, context, request, response, std::move(f));
}

void Query::Stub::async::SendBOTableInit(::grpc::ClientContext* context, const ::dbquery::InitBOTableRequest* request, ::dbquery::InitBOTableResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_SendBOTableInit_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::dbquery::InitBOTableResponse>* Query::Stub::PrepareAsyncSendBOTableInitRaw(::grpc::ClientContext* context, const ::dbquery::InitBOTableRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::dbquery::InitBOTableResponse, ::dbquery::InitBOTableRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_SendBOTableInit_, context, request);
}

::grpc::ClientAsyncResponseReader< ::dbquery::InitBOTableResponse>* Query::Stub::AsyncSendBOTableInitRaw(::grpc::ClientContext* context, const ::dbquery::InitBOTableRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncSendBOTableInitRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status Query::Stub::SendBOTableUpdate(::grpc::ClientContext* context, const ::dbquery::UpdateBOTableRequest& request, ::dbquery::UpdateBOTableResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::dbquery::UpdateBOTableRequest, ::dbquery::UpdateBOTableResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_SendBOTableUpdate_, context, request, response);
}

void Query::Stub::async::SendBOTableUpdate(::grpc::ClientContext* context, const ::dbquery::UpdateBOTableRequest* request, ::dbquery::UpdateBOTableResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::dbquery::UpdateBOTableRequest, ::dbquery::UpdateBOTableResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_SendBOTableUpdate_, context, request, response, std::move(f));
}

void Query::Stub::async::SendBOTableUpdate(::grpc::ClientContext* context, const ::dbquery::UpdateBOTableRequest* request, ::dbquery::UpdateBOTableResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_SendBOTableUpdate_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::dbquery::UpdateBOTableResponse>* Query::Stub::PrepareAsyncSendBOTableUpdateRaw(::grpc::ClientContext* context, const ::dbquery::UpdateBOTableRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::dbquery::UpdateBOTableResponse, ::dbquery::UpdateBOTableRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_SendBOTableUpdate_, context, request);
}

::grpc::ClientAsyncResponseReader< ::dbquery::UpdateBOTableResponse>* Query::Stub::AsyncSendBOTableUpdateRaw(::grpc::ClientContext* context, const ::dbquery::UpdateBOTableRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncSendBOTableUpdateRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status Query::Stub::SendBOTableBatchUpdate(::grpc::ClientContext* context, const ::dbquery::UpdateBOTableBatchRequest& request, ::dbquery::UpdateBOTableBatchResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::dbquery::UpdateBOTableBatchRequest, ::dbquery::UpdateBOTableBatchResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_SendBOTableBatchUpdate_, context, request, response);
}

void Query::Stub::async::SendBOTableBatchUpdate(::grpc::ClientContext* context, const ::dbquery::UpdateBOTableBatchRequest* request, ::dbquery::UpdateBOTableBatchResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::dbquery::UpdateBOTableBatchRequest, ::dbquery::UpdateBOTableBatchResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_SendBOTableBatchUpdate_, context, request, response, std::move(f));
}

void Query::Stub::async::SendBOTableBatchUpdate(::grpc::ClientContext* context, const ::dbquery::UpdateBOTableBatchRequest* request, ::dbquery::UpdateBOTableBatchResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_SendBOTableBatchUpdate_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::dbquery::UpdateBOTableBatchResponse>* Query::Stub::PrepareAsyncSendBOTableBatchUpdateRaw(::grpc::ClientContext* context, const ::dbquery::UpdateBOTableBatchRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::dbquery::UpdateBOTableBatchResponse, ::dbquery::UpdateBOTableBatchRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_SendBOTableBatchUpdate_, context, request);
}

::grpc::ClientAsyncResponseReader< ::dbquery::UpdateBOTableBatchResponse>* Query::Stub::AsyncSendBOTableBatchUpdateRaw(::grpc::ClientContext* context, const ::dbquery::UpdateBOTableBatchRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncSendBOTableBatchUpdateRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status Query::Stub::SendBOAggQuery(::grpc::ClientContext* context, const ::dbquery::QueryBOAggRequest& request, ::dbquery::QueryBOAggResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::dbquery::QueryBOAggRequest, ::dbquery::QueryBOAggResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_SendBOAggQuery_, context, request, response);
}

void Query::Stub::async::SendBOAggQuery(::grpc::ClientContext* context, const ::dbquery::QueryBOAggRequest* request, ::dbquery::QueryBOAggResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::dbquery::QueryBOAggRequest, ::dbquery::QueryBOAggResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_SendBOAggQuery_, context, request, response, std::move(f));
}

void Query::Stub::async::SendBOAggQuery(::grpc::ClientContext* context, const ::dbquery::QueryBOAggRequest* request, ::dbquery::QueryBOAggResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_SendBOAggQuery_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::dbquery::QueryBOAggResponse>* Query::Stub::PrepareAsyncSendBOAggQueryRaw(::grpc::ClientContext* context, const ::dbquery::QueryBOAggRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::dbquery::QueryBOAggResponse, ::dbquery::QueryBOAggRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_SendBOAggQuery_, context, request);
}

::grpc::ClientAsyncResponseReader< ::dbquery::QueryBOAggResponse>* Query::Stub::AsyncSendBOAggQueryRaw(::grpc::ClientContext* context, const ::dbquery::QueryBOAggRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncSendBOAggQueryRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status Query::Stub::SendVBFSSAggQuery(::grpc::ClientContext* context, const ::dbquery::QueryVBFSSAggRequest& request, ::dbquery::QueryVBFSSAggResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::dbquery::QueryVBFSSAggRequest, ::dbquery::QueryVBFSSAggResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_SendVBFSSAggQuery_, context, request, response);
}

void Query::Stub::async::SendVBFSSAggQuery(::grpc::ClientContext* context, const ::dbquery::QueryVBFSSAggRequest* request, ::dbquery::QueryVBFSSAggResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::dbquery::QueryVBFSSAggRequest, ::dbquery::QueryVBFSSAggResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_SendVBFSSAggQuery_, context, request, response, std::move(f));
}

void Query::Stub::async::SendVBFSSAggQuery(::grpc::ClientContext* context, const ::dbquery::QueryVBFSSAggRequest* request, ::dbquery::QueryVBFSSAggResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_SendVBFSSAggQuery_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::dbquery::QueryVBFSSAggResponse>* Query::Stub::PrepareAsyncSendVBFSSAggQueryRaw(::grpc::ClientContext* context, const ::dbquery::QueryVBFSSAggRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::dbquery::QueryVBFSSAggResponse, ::dbquery::QueryVBFSSAggRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_SendVBFSSAggQuery_, context, request);
}

::grpc::ClientAsyncResponseReader< ::dbquery::QueryVBFSSAggResponse>* Query::Stub::AsyncSendVBFSSAggQueryRaw(::grpc::ClientContext* context, const ::dbquery::QueryVBFSSAggRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncSendVBFSSAggQueryRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status Query::Stub::SendBOFSSAggQuery(::grpc::ClientContext* context, const ::dbquery::QueryBOFSSAggRequest& request, ::dbquery::QueryBOFSSAggResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::dbquery::QueryBOFSSAggRequest, ::dbquery::QueryBOFSSAggResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_SendBOFSSAggQuery_, context, request, response);
}

void Query::Stub::async::SendBOFSSAggQuery(::grpc::ClientContext* context, const ::dbquery::QueryBOFSSAggRequest* request, ::dbquery::QueryBOFSSAggResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::dbquery::QueryBOFSSAggRequest, ::dbquery::QueryBOFSSAggResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_SendBOFSSAggQuery_, context, request, response, std::move(f));
}

void Query::Stub::async::SendBOFSSAggQuery(::grpc::ClientContext* context, const ::dbquery::QueryBOFSSAggRequest* request, ::dbquery::QueryBOFSSAggResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_SendBOFSSAggQuery_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::dbquery::QueryBOFSSAggResponse>* Query::Stub::PrepareAsyncSendBOFSSAggQueryRaw(::grpc::ClientContext* context, const ::dbquery::QueryBOFSSAggRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::dbquery::QueryBOFSSAggResponse, ::dbquery::QueryBOFSSAggRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_SendBOFSSAggQuery_, context, request);
}

::grpc::ClientAsyncResponseReader< ::dbquery::QueryBOFSSAggResponse>* Query::Stub::AsyncSendBOFSSAggQueryRaw(::grpc::ClientContext* context, const ::dbquery::QueryBOFSSAggRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncSendBOFSSAggQueryRaw(context, request, cq);
  result->StartCall();
  return result;
}

Query::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      Query_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< Query::Service, ::dbquery::InitDCFRequest, ::dbquery::InitDCFResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](Query::Service* service,
             ::grpc::ServerContext* ctx,
             const ::dbquery::InitDCFRequest* req,
             ::dbquery::InitDCFResponse* resp) {
               return service->SendDCFInit(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      Query_method_names[1],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< Query::Service, ::dbquery::InitDPFRequest, ::dbquery::InitDPFResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](Query::Service* service,
             ::grpc::ServerContext* ctx,
             const ::dbquery::InitDPFRequest* req,
             ::dbquery::InitDPFResponse* resp) {
               return service->SendDPFInit(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      Query_method_names[2],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< Query::Service, ::dbquery::InitATRequest, ::dbquery::InitATResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](Query::Service* service,
             ::grpc::ServerContext* ctx,
             const ::dbquery::InitATRequest* req,
             ::dbquery::InitATResponse* resp) {
               return service->SendATInit(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      Query_method_names[3],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< Query::Service, ::dbquery::InitListRequest, ::dbquery::InitListResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](Query::Service* service,
             ::grpc::ServerContext* ctx,
             const ::dbquery::InitListRequest* req,
             ::dbquery::InitListResponse* resp) {
               return service->SendListInit(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      Query_method_names[4],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< Query::Service, ::dbquery::UpdateDCFRequest, ::dbquery::UpdateDCFResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](Query::Service* service,
             ::grpc::ServerContext* ctx,
             const ::dbquery::UpdateDCFRequest* req,
             ::dbquery::UpdateDCFResponse* resp) {
               return service->SendDCFUpdate(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      Query_method_names[5],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< Query::Service, ::dbquery::BatchedUpdateDCFRequest, ::dbquery::BatchedUpdateDCFResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](Query::Service* service,
             ::grpc::ServerContext* ctx,
             const ::dbquery::BatchedUpdateDCFRequest* req,
             ::dbquery::BatchedUpdateDCFResponse* resp) {
               return service->SendDCFBatchedUpdate(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      Query_method_names[6],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< Query::Service, ::dbquery::UpdateDPFRequest, ::dbquery::UpdateDPFResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](Query::Service* service,
             ::grpc::ServerContext* ctx,
             const ::dbquery::UpdateDPFRequest* req,
             ::dbquery::UpdateDPFResponse* resp) {
               return service->SendDPFUpdate(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      Query_method_names[7],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< Query::Service, ::dbquery::BatchedUpdateDPFRequest, ::dbquery::BatchedUpdateDPFResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](Query::Service* service,
             ::grpc::ServerContext* ctx,
             const ::dbquery::BatchedUpdateDPFRequest* req,
             ::dbquery::BatchedUpdateDPFResponse* resp) {
               return service->SendDPFBatchedUpdate(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      Query_method_names[8],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< Query::Service, ::dbquery::UpdateListRequest, ::dbquery::UpdateListResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](Query::Service* service,
             ::grpc::ServerContext* ctx,
             const ::dbquery::UpdateListRequest* req,
             ::dbquery::UpdateListResponse* resp) {
               return service->SendListUpdate(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      Query_method_names[9],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< Query::Service, ::dbquery::BatchedUpdateListRequest, ::dbquery::BatchedUpdateListResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](Query::Service* service,
             ::grpc::ServerContext* ctx,
             const ::dbquery::BatchedUpdateListRequest* req,
             ::dbquery::BatchedUpdateListResponse* resp) {
               return service->SendListBatchedUpdate(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      Query_method_names[10],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< Query::Service, ::dbquery::AppendAT1Request, ::dbquery::AppendAT1Response, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](Query::Service* service,
             ::grpc::ServerContext* ctx,
             const ::dbquery::AppendAT1Request* req,
             ::dbquery::AppendAT1Response* resp) {
               return service->SendATAppend1(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      Query_method_names[11],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< Query::Service, ::dbquery::AppendAT2Request, ::dbquery::AppendAT2Response, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](Query::Service* service,
             ::grpc::ServerContext* ctx,
             const ::dbquery::AppendAT2Request* req,
             ::dbquery::AppendAT2Response* resp) {
               return service->SendATAppend2(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      Query_method_names[12],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< Query::Service, ::dbquery::QueryDCFRequest, ::dbquery::QueryDCFResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](Query::Service* service,
             ::grpc::ServerContext* ctx,
             const ::dbquery::QueryDCFRequest* req,
             ::dbquery::QueryDCFResponse* resp) {
               return service->SendDCFQuery(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      Query_method_names[13],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< Query::Service, ::dbquery::QueryATRequest, ::dbquery::QueryATResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](Query::Service* service,
             ::grpc::ServerContext* ctx,
             const ::dbquery::QueryATRequest* req,
             ::dbquery::QueryATResponse* resp) {
               return service->SendATQuery(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      Query_method_names[14],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< Query::Service, ::dbquery::QueryAggRequest, ::dbquery::QueryAggResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](Query::Service* service,
             ::grpc::ServerContext* ctx,
             const ::dbquery::QueryAggRequest* req,
             ::dbquery::QueryAggResponse* resp) {
               return service->SendAggQuery(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      Query_method_names[15],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< Query::Service, ::dbquery::QueryVBAggRequest, ::dbquery::QueryVBAggResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](Query::Service* service,
             ::grpc::ServerContext* ctx,
             const ::dbquery::QueryVBAggRequest* req,
             ::dbquery::QueryVBAggResponse* resp) {
               return service->SendVBAggQuery(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      Query_method_names[16],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< Query::Service, ::dbquery::UpdateOneHotTableRequest, ::dbquery::UpdateOneHotTableResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](Query::Service* service,
             ::grpc::ServerContext* ctx,
             const ::dbquery::UpdateOneHotTableRequest* req,
             ::dbquery::UpdateOneHotTableResponse* resp) {
               return service->SendOneHotTableUpdate(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      Query_method_names[17],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< Query::Service, ::dbquery::UpdateOneHotTableBatchRequest, ::dbquery::UpdateOneHotTableBatchResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](Query::Service* service,
             ::grpc::ServerContext* ctx,
             const ::dbquery::UpdateOneHotTableBatchRequest* req,
             ::dbquery::UpdateOneHotTableBatchResponse* resp) {
               return service->SendOneHotTableBatchUpdate(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      Query_method_names[18],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< Query::Service, ::dbquery::InitOneHotTableRequest, ::dbquery::InitOneHotTableResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](Query::Service* service,
             ::grpc::ServerContext* ctx,
             const ::dbquery::InitOneHotTableRequest* req,
             ::dbquery::InitOneHotTableResponse* resp) {
               return service->SendOneHotTableInit(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      Query_method_names[19],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< Query::Service, ::dbquery::InitBOTableRequest, ::dbquery::InitBOTableResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](Query::Service* service,
             ::grpc::ServerContext* ctx,
             const ::dbquery::InitBOTableRequest* req,
             ::dbquery::InitBOTableResponse* resp) {
               return service->SendBOTableInit(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      Query_method_names[20],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< Query::Service, ::dbquery::UpdateBOTableRequest, ::dbquery::UpdateBOTableResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](Query::Service* service,
             ::grpc::ServerContext* ctx,
             const ::dbquery::UpdateBOTableRequest* req,
             ::dbquery::UpdateBOTableResponse* resp) {
               return service->SendBOTableUpdate(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      Query_method_names[21],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< Query::Service, ::dbquery::UpdateBOTableBatchRequest, ::dbquery::UpdateBOTableBatchResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](Query::Service* service,
             ::grpc::ServerContext* ctx,
             const ::dbquery::UpdateBOTableBatchRequest* req,
             ::dbquery::UpdateBOTableBatchResponse* resp) {
               return service->SendBOTableBatchUpdate(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      Query_method_names[22],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< Query::Service, ::dbquery::QueryBOAggRequest, ::dbquery::QueryBOAggResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](Query::Service* service,
             ::grpc::ServerContext* ctx,
             const ::dbquery::QueryBOAggRequest* req,
             ::dbquery::QueryBOAggResponse* resp) {
               return service->SendBOAggQuery(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      Query_method_names[23],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< Query::Service, ::dbquery::QueryVBFSSAggRequest, ::dbquery::QueryVBFSSAggResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](Query::Service* service,
             ::grpc::ServerContext* ctx,
             const ::dbquery::QueryVBFSSAggRequest* req,
             ::dbquery::QueryVBFSSAggResponse* resp) {
               return service->SendVBFSSAggQuery(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      Query_method_names[24],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< Query::Service, ::dbquery::QueryBOFSSAggRequest, ::dbquery::QueryBOFSSAggResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](Query::Service* service,
             ::grpc::ServerContext* ctx,
             const ::dbquery::QueryBOFSSAggRequest* req,
             ::dbquery::QueryBOFSSAggResponse* resp) {
               return service->SendBOFSSAggQuery(ctx, req, resp);
             }, this)));
}

Query::Service::~Service() {
}

::grpc::Status Query::Service::SendDCFInit(::grpc::ServerContext* context, const ::dbquery::InitDCFRequest* request, ::dbquery::InitDCFResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status Query::Service::SendDPFInit(::grpc::ServerContext* context, const ::dbquery::InitDPFRequest* request, ::dbquery::InitDPFResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status Query::Service::SendATInit(::grpc::ServerContext* context, const ::dbquery::InitATRequest* request, ::dbquery::InitATResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status Query::Service::SendListInit(::grpc::ServerContext* context, const ::dbquery::InitListRequest* request, ::dbquery::InitListResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status Query::Service::SendDCFUpdate(::grpc::ServerContext* context, const ::dbquery::UpdateDCFRequest* request, ::dbquery::UpdateDCFResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status Query::Service::SendDCFBatchedUpdate(::grpc::ServerContext* context, const ::dbquery::BatchedUpdateDCFRequest* request, ::dbquery::BatchedUpdateDCFResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status Query::Service::SendDPFUpdate(::grpc::ServerContext* context, const ::dbquery::UpdateDPFRequest* request, ::dbquery::UpdateDPFResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status Query::Service::SendDPFBatchedUpdate(::grpc::ServerContext* context, const ::dbquery::BatchedUpdateDPFRequest* request, ::dbquery::BatchedUpdateDPFResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status Query::Service::SendListUpdate(::grpc::ServerContext* context, const ::dbquery::UpdateListRequest* request, ::dbquery::UpdateListResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status Query::Service::SendListBatchedUpdate(::grpc::ServerContext* context, const ::dbquery::BatchedUpdateListRequest* request, ::dbquery::BatchedUpdateListResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status Query::Service::SendATAppend1(::grpc::ServerContext* context, const ::dbquery::AppendAT1Request* request, ::dbquery::AppendAT1Response* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status Query::Service::SendATAppend2(::grpc::ServerContext* context, const ::dbquery::AppendAT2Request* request, ::dbquery::AppendAT2Response* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status Query::Service::SendDCFQuery(::grpc::ServerContext* context, const ::dbquery::QueryDCFRequest* request, ::dbquery::QueryDCFResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status Query::Service::SendATQuery(::grpc::ServerContext* context, const ::dbquery::QueryATRequest* request, ::dbquery::QueryATResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status Query::Service::SendAggQuery(::grpc::ServerContext* context, const ::dbquery::QueryAggRequest* request, ::dbquery::QueryAggResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status Query::Service::SendVBAggQuery(::grpc::ServerContext* context, const ::dbquery::QueryVBAggRequest* request, ::dbquery::QueryVBAggResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status Query::Service::SendOneHotTableUpdate(::grpc::ServerContext* context, const ::dbquery::UpdateOneHotTableRequest* request, ::dbquery::UpdateOneHotTableResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status Query::Service::SendOneHotTableBatchUpdate(::grpc::ServerContext* context, const ::dbquery::UpdateOneHotTableBatchRequest* request, ::dbquery::UpdateOneHotTableBatchResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status Query::Service::SendOneHotTableInit(::grpc::ServerContext* context, const ::dbquery::InitOneHotTableRequest* request, ::dbquery::InitOneHotTableResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status Query::Service::SendBOTableInit(::grpc::ServerContext* context, const ::dbquery::InitBOTableRequest* request, ::dbquery::InitBOTableResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status Query::Service::SendBOTableUpdate(::grpc::ServerContext* context, const ::dbquery::UpdateBOTableRequest* request, ::dbquery::UpdateBOTableResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status Query::Service::SendBOTableBatchUpdate(::grpc::ServerContext* context, const ::dbquery::UpdateBOTableBatchRequest* request, ::dbquery::UpdateBOTableBatchResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status Query::Service::SendBOAggQuery(::grpc::ServerContext* context, const ::dbquery::QueryBOAggRequest* request, ::dbquery::QueryBOAggResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status Query::Service::SendVBFSSAggQuery(::grpc::ServerContext* context, const ::dbquery::QueryVBFSSAggRequest* request, ::dbquery::QueryVBFSSAggResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status Query::Service::SendBOFSSAggQuery(::grpc::ServerContext* context, const ::dbquery::QueryBOFSSAggRequest* request, ::dbquery::QueryBOFSSAggResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


static const char* Aggregate_method_names[] = {
  "/dbquery.Aggregate/SendMult",
  "/dbquery.Aggregate/SendSystemInit",
};

std::unique_ptr< Aggregate::Stub> Aggregate::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< Aggregate::Stub> stub(new Aggregate::Stub(channel, options));
  return stub;
}

Aggregate::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options)
  : channel_(channel), rpcmethod_SendMult_(Aggregate_method_names[0], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_SendSystemInit_(Aggregate_method_names[1], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status Aggregate::Stub::SendMult(::grpc::ClientContext* context, const ::dbquery::MultRequest& request, ::dbquery::MultResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::dbquery::MultRequest, ::dbquery::MultResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_SendMult_, context, request, response);
}

void Aggregate::Stub::async::SendMult(::grpc::ClientContext* context, const ::dbquery::MultRequest* request, ::dbquery::MultResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::dbquery::MultRequest, ::dbquery::MultResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_SendMult_, context, request, response, std::move(f));
}

void Aggregate::Stub::async::SendMult(::grpc::ClientContext* context, const ::dbquery::MultRequest* request, ::dbquery::MultResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_SendMult_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::dbquery::MultResponse>* Aggregate::Stub::PrepareAsyncSendMultRaw(::grpc::ClientContext* context, const ::dbquery::MultRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::dbquery::MultResponse, ::dbquery::MultRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_SendMult_, context, request);
}

::grpc::ClientAsyncResponseReader< ::dbquery::MultResponse>* Aggregate::Stub::AsyncSendMultRaw(::grpc::ClientContext* context, const ::dbquery::MultRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncSendMultRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status Aggregate::Stub::SendSystemInit(::grpc::ClientContext* context, const ::dbquery::InitSystemRequest& request, ::dbquery::InitSystemResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::dbquery::InitSystemRequest, ::dbquery::InitSystemResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_SendSystemInit_, context, request, response);
}

void Aggregate::Stub::async::SendSystemInit(::grpc::ClientContext* context, const ::dbquery::InitSystemRequest* request, ::dbquery::InitSystemResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::dbquery::InitSystemRequest, ::dbquery::InitSystemResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_SendSystemInit_, context, request, response, std::move(f));
}

void Aggregate::Stub::async::SendSystemInit(::grpc::ClientContext* context, const ::dbquery::InitSystemRequest* request, ::dbquery::InitSystemResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_SendSystemInit_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::dbquery::InitSystemResponse>* Aggregate::Stub::PrepareAsyncSendSystemInitRaw(::grpc::ClientContext* context, const ::dbquery::InitSystemRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::dbquery::InitSystemResponse, ::dbquery::InitSystemRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_SendSystemInit_, context, request);
}

::grpc::ClientAsyncResponseReader< ::dbquery::InitSystemResponse>* Aggregate::Stub::AsyncSendSystemInitRaw(::grpc::ClientContext* context, const ::dbquery::InitSystemRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncSendSystemInitRaw(context, request, cq);
  result->StartCall();
  return result;
}

Aggregate::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      Aggregate_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< Aggregate::Service, ::dbquery::MultRequest, ::dbquery::MultResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](Aggregate::Service* service,
             ::grpc::ServerContext* ctx,
             const ::dbquery::MultRequest* req,
             ::dbquery::MultResponse* resp) {
               return service->SendMult(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      Aggregate_method_names[1],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< Aggregate::Service, ::dbquery::InitSystemRequest, ::dbquery::InitSystemResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](Aggregate::Service* service,
             ::grpc::ServerContext* ctx,
             const ::dbquery::InitSystemRequest* req,
             ::dbquery::InitSystemResponse* resp) {
               return service->SendSystemInit(ctx, req, resp);
             }, this)));
}

Aggregate::Service::~Service() {
}

::grpc::Status Aggregate::Service::SendMult(::grpc::ServerContext* context, const ::dbquery::MultRequest* request, ::dbquery::MultResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status Aggregate::Service::SendSystemInit(::grpc::ServerContext* context, const ::dbquery::InitSystemRequest* request, ::dbquery::InitSystemResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace dbquery

