# Generated by CMake

if("${CMAKE_MAJOR_VERSION}.${CMAKE_MINOR_VERSION}" LESS 2.8)
   message(FATAL_ERROR "CMake >= 2.8.0 required")
endif()
if(CMAKE_VERSION VERSION_LESS "2.8.3")
   message(FATAL_ERROR "CMake >= 2.8.3 required")
endif()
cmake_policy(PUSH)
cmake_policy(VERSION 2.8.3...3.26)
#----------------------------------------------------------------
# Generated CMake target import file.
#----------------------------------------------------------------

# Commands may need to know the format version.
set(CMAKE_IMPORT_FILE_VERSION 1)

# Protect against multiple inclusion, which would fail when already imported targets are added once more.
set(_cmake_targets_defined "")
set(_cmake_targets_not_defined "")
set(_cmake_expected_targets "")
foreach(_cmake_expected_target IN ITEMS libOTe_Tests libOTe cryptoTools)
  list(APPEND _cmake_expected_targets "${_cmake_expected_target}")
  if(TARGET "${_cmake_expected_target}")
    list(APPEND _cmake_targets_defined "${_cmake_expected_target}")
  else()
    list(APPEND _cmake_targets_not_defined "${_cmake_expected_target}")
  endif()
endforeach()
unset(_cmake_expected_target)
if(_cmake_targets_defined STREQUAL _cmake_expected_targets)
  unset(_cmake_targets_defined)
  unset(_cmake_targets_not_defined)
  unset(_cmake_expected_targets)
  unset(CMAKE_IMPORT_FILE_VERSION)
  cmake_policy(POP)
  return()
endif()
if(NOT _cmake_targets_defined STREQUAL "")
  string(REPLACE ";" ", " _cmake_targets_defined_text "${_cmake_targets_defined}")
  string(REPLACE ";" ", " _cmake_targets_not_defined_text "${_cmake_targets_not_defined}")
  message(FATAL_ERROR "Some (but not all) targets in this export set were already defined.\nTargets Defined: ${_cmake_targets_defined_text}\nTargets not yet defined: ${_cmake_targets_not_defined_text}\n")
endif()
unset(_cmake_targets_defined)
unset(_cmake_targets_not_defined)
unset(_cmake_expected_targets)


# Create imported target libOTe_Tests
add_library(libOTe_Tests STATIC IMPORTED)

set_target_properties(libOTe_Tests PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "/home/tomato/git_project/waldo/fss-core/libOTe"
)

# Create imported target libOTe
add_library(libOTe STATIC IMPORTED)

set_target_properties(libOTe PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "/home/tomato/git_project/waldo/fss-core/libOTe/libOTe/..;/home/tomato/git_project/waldo/fss-core/libOTe/libOTe/.."
)

# Create imported target cryptoTools
add_library(cryptoTools STATIC IMPORTED)

set_target_properties(cryptoTools PROPERTIES
  INTERFACE_COMPILE_OPTIONS "\$<\$<COMPILE_LANGUAGE:CXX>:-std=c++14>;-pthread;-maes;-msse2;-msse3;-msse4.1;-mpclmul"
  INTERFACE_INCLUDE_DIRECTORIES "/home/tomato/git_project/waldo/fss-core/libOTe/cryptoTools/cryptoTools/..;/home/tomato/git_project/waldo/fss-core/libOTe/cryptoTools/cryptoTools/..;/home/tomato/.local/include;/usr/include"
  INTERFACE_LINK_OPTIONS "-pthread"
)

# Import target "libOTe_Tests" for configuration "Release"
set_property(TARGET libOTe_Tests APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(libOTe_Tests PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELEASE "CXX"
  IMPORTED_LINK_INTERFACE_LIBRARIES_RELEASE "libOTe"
  IMPORTED_LOCATION_RELEASE "/home/tomato/git_project/waldo/fss-core/libOTe/libOTe_Tests/liblibOTe_Tests.a"
  )

# Import target "libOTe" for configuration "Release"
set_property(TARGET libOTe APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(libOTe PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELEASE "CXX"
  IMPORTED_LINK_INTERFACE_LIBRARIES_RELEASE "OpenMP::OpenMP_CXX;cryptoTools"
  IMPORTED_LOCATION_RELEASE "/home/tomato/git_project/waldo/fss-core/libOTe/libOTe/liblibOTe.a"
  )

# Import target "cryptoTools" for configuration "Release"
set_property(TARGET cryptoTools APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(cryptoTools PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELEASE "C;CXX"
  IMPORTED_LINK_INTERFACE_LIBRARIES_RELEASE "/home/tomato/.local/lib/librelic.so;Boost::system;Boost::thread"
  IMPORTED_LOCATION_RELEASE "/home/tomato/git_project/waldo/fss-core/libOTe/cryptoTools/cryptoTools/libcryptoTools.a"
  )

# This file does not depend on other imported targets which have
# been exported from the same project but in a separate export set.

# Commands beyond this point should not need to know the version.
set(CMAKE_IMPORT_FILE_VERSION)
cmake_policy(POP)
